### ISSUE TITLE
Shapeless produces 'Referring to non-existent method' erros during fast optimization

### ISSUE THREAD

**Issue by tymm** [scalajs-react-interface/sbt-sri-platform#1]
When I try to use circe (and therefore shapeless) in sri (with sbt-sri-platform-2017.4.10-beta), I get a bunch of `Referring to non-existent method` errors during fast optimization. Compiling works fine.

Errors look like this or similar:
```
[error] Referring to non-existent class shapeless.Lazy$
```

I created a repository which reproduces this issue:
https://github.com/tymm/sri-circe-bug

Removing https://github.com/scalajs-react-interface/sbt-sri-platform/blob/a252591b3aebf4ee2b77f888706e35d482c9e6c7/src/main/scala/sri/sbt/platform/ConfigBuilder.scala#L62 seems to solve the issue.

Can you share some insights on what exactly is happening at line 62 in `ConfigBuilder.scala` and if we can just remove it?

**Comment by chandu0101** [comment]
@tymm  good catch! , when i am first writing this plugin  i didn't used `ScalaJSPluginInternal.scalaJSConfigSettings`. `ScalaJSPluginInternal.someothersettings`  asked me to provide `fullClassPath`. 

remove the fullClassPath and  send a PR 👍

**Comment by chandu0101** [comment]
closed via #2
